# Generated by Django 5.0 on 2023-12-30 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0003_remove_cotizacion_comision_dxb_and_more'),
        ('comercial', '0006_alter_historicalpedido_tasa_representativa_usd_diaria_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cotizacion',
            new_name='CotizacionEtnico',
        ),
    ]
