# Generated by Django 5.0 on 2023-12-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='propiedad_heavens',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Propiedad Heavens'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='traslado_propio',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Traslado Propio'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='traslado_remisionado',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Traslado Remisionado'),
        ),
    ]
