# Generated by Django 5.0 on 2023-12-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_remove_inventario_propiedad_heavens'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='venta_contenedor',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Venta Contenedor'),
        ),
    ]
