# Generated by Django 5.0.1 on 2024-01-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0004_inventario_venta_contenedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Proveedor'),
        ),
    ]
