# Generated by Django 5.0 on 2023-12-19 00:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='tarifa_comision',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarifa Comisión'),
        ),
    ]
