# Generated by Django 5.0.1 on 2024-01-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='presentacion',
            name='fruta',
        ),
    ]
