# Generated by Django 5.0.1 on 2024-01-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_alter_pedido_options_remove_presentacion_fruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='presentacion_peso',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True, verbose_name='Peso Presentacion'),
        ),
        migrations.AlterField(
            model_name='historicaldetallepedido',
            name='presentacion_peso',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True, verbose_name='Peso Presentacion'),
        ),
    ]
