# Generated by Django 5.0 on 2023-12-24 04:14

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_alter_detallepedido_tarifa_comision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPedido',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(blank=True, null=True, verbose_name='Fecha Solicitud')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha Entrega')),
                ('dias_cartera', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Dias Cartera')),
                ('awb', models.CharField(blank=True, max_length=50, null=True, verbose_name='AWB')),
                ('destino', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Destino')),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Factura')),
                ('total_cajas_enviadas', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Total Cajas Enviadas')),
                ('nota_credito_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota credito')),
                ('motivo_nota_credito', models.CharField(blank=True, choices=[('Calidad', 'Calidad'), ('Faltantes', 'Faltantes'), ('Precio', 'Precio')], max_length=20, null=True, verbose_name='Motivo Nota credito')),
                ('valor_total_nota_credito_usd', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Total Nota Credito')),
                ('tasa_representativa_usd_diaria', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='TRM Representativa')),
                ('valor_pagado_cliente_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Pagado Cliente')),
                ('comision_bancaria_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Comision Bancaria USD')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha Pago')),
                ('trm_monetizacion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='TRM Monetizacion')),
                ('estado_factura', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Estado Factura')),
                ('diferencia_por_abono', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Diferencia o Abono')),
                ('dias_de_vencimiento', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Dias Vencimiento')),
                ('valor_total_factura_usd', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Valor Total Factura')),
                ('valor_total_comision_usd', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Valor Total Comision USD')),
                ('valor_comision_pesos', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Valor Total Comision Pesos')),
                ('documento_cobro_comision', models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento Cobro Comision')),
                ('fecha_pago_comision', models.DateField(blank=True, null=True, verbose_name='Fecha De Pago Comision')),
                ('estado_comision', models.CharField(editable=False, max_length=50, verbose_name='Estado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comercial.cliente', verbose_name='Cliente')),
                ('exportadora', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comercial.exportador', verbose_name='Exportador')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pedido',
                'verbose_name_plural': 'historical pedidos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
