# Generated by Django 5.0 on 2023-12-24 04:24

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_historicalpedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDetallePedido',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cajas_solicitadas', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cajas Solicitadas')),
                ('presentacion_peso', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=3, null=True, verbose_name='Peso Presentacion')),
                ('kilos', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Kilos')),
                ('cajas_enviadas', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cajas Enviadas')),
                ('kilos_enviados', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Kilos Enviados')),
                ('diferencia', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Diferencia')),
                ('stickers', models.CharField(blank=True, editable=False, null=True, verbose_name='Stikers')),
                ('lleva_contenedor', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], verbose_name='LLeva Contenedor')),
                ('referencia_contenedor', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Referencia Contenedor')),
                ('cantidad_contenedores', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Cantidad Contenedores')),
                ('tarifa_comision', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarifa Comisión')),
                ('valor_x_caja_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor X Caja USD')),
                ('valor_x_producto', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Valor X Producto')),
                ('no_cajas_nc', models.IntegerField(blank=True, null=True, verbose_name='No Cajas NC')),
                ('valor_nota_credito_usd', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Valor Nota Credito USD')),
                ('afecta_comision', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], null=True, verbose_name='Afecta Comision')),
                ('valor_total_comision_x_producto', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Valor Comision X Producto')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fruta', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comercial.fruta', verbose_name='Fruta')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comercial.pedido', verbose_name='Pedido')),
                ('presentacion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comercial.presentacion', verbose_name='Presentacion')),
                ('referencia', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comercial.referencias', verbose_name='Referencia')),
                ('tipo_caja', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comercial.tipocaja', verbose_name='Tipo De Caja')),
            ],
            options={
                'verbose_name': 'historical detalle pedido',
                'verbose_name_plural': 'historical detalle pedidos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
