# Generated by Django 5.0.1 on 2024-01-16 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_alter_detallepedido_presentacion_peso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'ordering': ['pedido']},
        ),
    ]
