# Generated by Django 5.0 on 2023-12-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_historicaldetallepedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpedido',
            name='fecha_entrega',
            field=models.DateField(verbose_name='Fecha Entrega'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='fecha_solicitud',
            field=models.DateField(verbose_name='Fecha Solicitud'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateField(verbose_name='Fecha Entrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_solicitud',
            field=models.DateField(verbose_name='Fecha Solicitud'),
        ),
    ]
