# Generated by Django 5.0.1 on 2024-01-16 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_alter_detallepedido_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePresentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.cliente')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.presentacion')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='presentaciones',
            field=models.ManyToManyField(related_name='clientes', through='comercial.ClientePresentacion', to='comercial.presentacion'),
        ),
    ]
