# Generated by Django 5.0.1 on 2024-01-19 03:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_clientepresentacion_cliente_presentaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientepresentacion',
            options={'ordering': ['cliente']},
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='observaciones',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='historicaldetallepedido',
            name='observaciones',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='afecta_comision',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], null=True, verbose_name='Afecta Comisión'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad_contenedores',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='No. Contenedores'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='kilos',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Kilos Netos'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.presentacion', verbose_name='Presentación'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='presentacion_peso',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True, verbose_name='Peso Caja'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='referencia_contenedor',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Contenedor'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='stickers',
            field=models.CharField(blank=True, editable=False, null=True, verbose_name='Stickers'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='tarifa_comision',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='$Comisión Por Caja'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='tipo_caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.tipocaja', verbose_name='Marca Caja'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='valor_nota_credito_usd',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='$Nota Crédito USD'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='valor_total_comision_x_producto',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='$Comisión X Producto'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='valor_x_caja_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='$Por Caja USD'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='valor_x_producto',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='$Por Producto'),
        ),
        migrations.AlterField(
            model_name='historicaldetallepedido',
            name='afecta_comision',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], null=True, verbose_name='Afecta Comisión'),
        ),
        migrations.AlterField(
            model_name='historicaldetallepedido',
            name='cantidad_contenedores',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='No. Contenedores'),
        ),
        migrations.AlterField(
            model_name='historicaldetallepedido',
            name='kilos',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Kilos Netos'),
        ),
        migrations.AlterField(
            model_name='historicaldetallepedido',
            name='presentacion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comercial.presentacion', verbose_name='Presentación'),
        ),
        migrations.AlterField(
            model_name='historicaldetallepedido',
            name='presentacion_peso',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True, verbose_name='Peso Caja'),
        ),
        migrations.AlterField(
            model_name='historicaldetallepedido',
            name='referencia_contenedor',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Contenedor'),
        ),
        migrations.AlterField(
            model_name='historicaldetallepedido',
            name='stickers',
            field=models.CharField(blank=True, editable=False, null=True, verbose_name='Stickers'),
        ),
        migrations.AlterField(
            model_name='historicaldetallepedido',
            name='tarifa_comision',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='$Comisión Por Caja'),
        ),
        migrations.AlterField(
            model_name='historicaldetallepedido',
            name='tipo_caja',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comercial.tipocaja', verbose_name='Marca Caja'),
        ),
        migrations.AlterField(
            model_name='historicaldetallepedido',
            name='valor_nota_credito_usd',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='$Nota Crédito USD'),
        ),
        migrations.AlterField(
            model_name='historicaldetallepedido',
            name='valor_total_comision_x_producto',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='$Comisión X Producto'),
        ),
        migrations.AlterField(
            model_name='historicaldetallepedido',
            name='valor_x_caja_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='$Por Caja USD'),
        ),
        migrations.AlterField(
            model_name='historicaldetallepedido',
            name='valor_x_producto',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='$Por Producto'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='comision_bancaria_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='$Comisión Bancaria USD'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='documento_cobro_comision',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Doc Cobro Comisión'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='estado_comision',
            field=models.CharField(editable=False, max_length=50, verbose_name='Estado Comisión'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='fecha_pago_comision',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Pago Comisión'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='motivo_nota_credito',
            field=models.CharField(blank=True, choices=[('Calidad', 'Calidad'), ('Faltantes', 'Faltantes'), ('Precio', 'Precio')], max_length=20, null=True, verbose_name='Motivo Nota Crédito'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='nota_credito_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota Crédito'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='tasa_representativa_usd_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='$TRM Oficial'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='total_cajas_enviadas',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Cajas Enviadas'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='trm_monetizacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='$TRM Monetización'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='valor_comision_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='$Comisiones Pesos'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='valor_pagado_cliente_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='$Pagado Cliente'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='valor_total_comision_usd',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='$Comisiones USD'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='valor_total_factura_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='$Total Factura'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='valor_total_nota_credito_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='$Total Nota Crédito'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='comision_bancaria_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='$Comisión Bancaria USD'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='documento_cobro_comision',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Doc Cobro Comisión'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_comision',
            field=models.CharField(editable=False, max_length=50, verbose_name='Estado Comisión'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pago_comision',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Pago Comisión'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='motivo_nota_credito',
            field=models.CharField(blank=True, choices=[('Calidad', 'Calidad'), ('Faltantes', 'Faltantes'), ('Precio', 'Precio')], max_length=20, null=True, verbose_name='Motivo Nota Crédito'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nota_credito_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota Crédito'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tasa_representativa_usd_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='$TRM Oficial'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total_cajas_enviadas',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Cajas Enviadas'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='trm_monetizacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='$TRM Monetización'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_comision_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='$Comisiones Pesos'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_pagado_cliente_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='$Pagado Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_total_comision_usd',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='$Comisiones USD'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_total_factura_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='$Total Factura'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_total_nota_credito_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='$Total Nota Crédito'),
        ),
        migrations.AlterField(
            model_name='presentacion',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Presentación'),
        ),
    ]
