# Generated by Django 5.0 on 2023-12-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_alter_historicalpedido_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpedido',
            name='tasa_representativa_usd_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='TRM Representativa'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tasa_representativa_usd_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='TRM Representativa'),
        ),
    ]
