# Generated by Django 5.0 on 2024-01-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_alter_historicalpedido_tasa_representativa_usd_diaria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'ordering': ['fruta']},
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='estado_comision',
            field=models.CharField(editable=False, max_length=50, verbose_name='Estado Com'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_comision',
            field=models.CharField(editable=False, max_length=50, verbose_name='Estado Com'),
        ),
    ]
