# Generated by Django 5.0.1 on 2024-01-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_alter_clientepresentacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='precio_proforma',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='$Proforma'),
        ),
        migrations.AddField(
            model_name='historicaldetallepedido',
            name='precio_proforma',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='$Proforma'),
        ),
    ]
