# Generated by Django 5.0.1 on 2024-01-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0007_alter_detallepedido_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruta',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
