# Generated by Django 5.0.1 on 2024-01-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0008_alter_fruta_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre Cliente'),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre del Contenedor'),
        ),
        migrations.AlterField(
            model_name='exportador',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='presentacion',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Presentacion'),
        ),
        migrations.AlterField(
            model_name='referencias',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='tipocaja',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tipo De Caja'),
        ),
    ]
