# Generated by Django 5.0.1 on 2024-01-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0009_alter_cliente_nombre_alter_contenedor_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencias',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Referencia'),
        ),
    ]
